# Generated by Django 5.2.4 on 2025-07-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
